### ISSUE TITLE
in /get_scanner catch exceptions.AuthenticationFailed

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#110]
the view /get_scanner should catch exceptions.AuthenticationFailed  which cna be raised by teh call to authenticate()

**Comment by ampotos** [comment]
Also cehck every use of this auth function tu add apropriate except if missing

**Comment by fr0gRIP** [comment]
Didn't find any other non-catched exception for the moment

**Comment by ampotos** [comment]
I wasn't sure there is any, my comment was just here to remember the person who will fix the issue to check.
So it's ok ^^
