### ISSUE TITLE
[Vuln] check if the station is owned by the user (get_scanner)

### ISSUE THREAD

**Issue by fr0gRIP** [vigilate/backend#114]
get_scanner method allow any member to download the scanner configured for any station

I created an user (test@test.com:test) and a station for him (station_id = 1)
a second user account (haha@haha.fr:test)

curl -u haha@haha.fr:test "http://172.16.84.128:1337/get_scanner/1/" -> works (it should not)

So we have to check if the user who made the request is the owner of the requested station

**Comment by ampotos** [comment]
after the authenticate we have to check the station is own by the auth user

**Comment by fr0gRIP** [comment]
I finish the #110 and I fix it
