### ISSUE TITLE
add detail in error returned when session is not created

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#151]

**Comment by eax64** [comment]
On every error responses.
We also should change the 403 of when there is no pwd/email given by a 400.

And we should also give a message when there is an error on user creation. (I think there is no message, but i'm not sure why)

**Comment by eax64** [comment]
I'll do it with {field_name: [err_msg]} instead of the {"detail": err_msg} so that the frontend can have a better handling of the error.
(It is almost done)
