### ISSUE TITLE
remove warning

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#18]
When the server start there is multiple warning with the RemovedInDjango110Warning keyword

They must be removed for us to be able to update django easily in the future.

**Comment by fr0gRIP** [comment]
I personnaly don't see anything :/

**Comment by ampotos** [comment]
what version of django are you using in your vm ?

**Comment by ampotos** [comment]
When look to /api/v1/users in my browser via the test server the following warning apear in the console
-RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()
-RemovedInDjango110Warning: 'get_all_related_many_to_many_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
- RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext
-RemovedInDjango110Warning: render() must be called with a dict, not a Context

**Comment by ampotos** [comment]
Fix by updating django rest framework after updating django.
