### ISSUE TITLE
by hand program adding don't check station

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#88]
in the case only 1 program is add, the station of the program is not check (see multi program adding).

**Comment by fr0gRIP** [comment]
Can you devlop ? Don't see what you wanna mean by "check the station" :s

**Comment by ampotos** [comment]
when only 1 prog is add, the code is not handle in the same way than when multiple prog is add.
In the case of only one prog the station is not check properly. During the demo kevin noticed than a program add in 1 station via the frontend will update the version for all station of the concerned user
